{% set version = "4.3.1" %}

package:
  name: omniorbpy
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/omniorb/files/omniORBpy/omniORBpy-{{ version }}/omniORBpy-{{ version }}.tar.bz2
  sha256: 9da34af0a0230ea0de793be73ee66dc8a87e732fec80437ea91222e272d01be2

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - make
  host:
    - python
    - omniorb
    - openssl
  run:
    - python
    - omniorb

test:
  source_files:
    - python3/omniidl_be
    - examples/echo/example_echo.idl
  commands:
    - omniidl -ppython3/omniidl_be -bpython examples/echo/example_echo.idl

about:
  home: http://omniorb.sourceforge.net/index.html
  license: GPL-2.0-only
  license_file: COPYING.LIB
  summary: Robust high performance CORBA ORB for C++ and Python

  description: |
    omniORB is an Object Request Broker (ORB) which implements
    specification 2.6 of the Common Object Request Broker Architecture
    (CORBA). omniORBpy is a Python mapping for omniORB.
  doc_url: http://omniorb.sourceforge.net/docs.html
  dev_url: https://sourceforge.net/projects/omniorb/

extra:
  recipe-maintainers:
    - carlodri
    - lockhart
