travis:
  secure:
    BINSTAR_TOKEN: nn+QLh0GgDHKPR9STj9e33jU4Pbk4+sTu4JUuNJFbHmeLofcEhyAMvQyrvAKny0m1IYJBy4pw5DdZf+jywvbW85PID/bgnqrNkqdDab0bAr56N31S3CqwlXc1K1FDQdV5oDSzhmW6CRuRmeM71uW3TO5dIqz4orX3b0x3eGhMlSdBaz8goTBgKU2+9MSzSKgC4aT8mJDyZhKnZqT7+7VVa6iAB+ySOk+RfwFzR5ot2RUGUQ3Bklz83YpSqUQyoecNVq6zAS1EGVE97KbDAtOYQ1BknZpxMXDYQ60sQuRqbYdegt2UY+ACffN6ybnvjaoGzdLNxIg7oPC4raAAea3pyb9dc0nfQHkuMw43xoimxGfPmP0B4vOn9ZDQO4rqOVF5SwDhXLWIgrgp8fA9sspHRBn7TCI97nvGQlIuF7APAe9yKYNf6v25Um5QveovmyGZzetkXD+Vr8mmOAWxZVi8PJVId6HjpIS45t5H+Pezb84iZ4aUaZH/fZkgG2rbcqyRMZyiMKXOD3L70NFcNImAVKyaM7lANJQ5J2lrExSzI/n5yfMOUS7x7PC6dNAax4vHL9BGg/UzwVs87QSan6Pj4+iPcNm5DhlMAhndLRvWXQirhV7sXoC5CdexSWBRLdZKu9XTx86PPAfER8KdEWARZ+279KrveyAyBhhJCQCUKc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
